config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  
  resources :postimages, only: [:new, :create, :index, :show]
  
  get 'homes/about', to: 'homes#about' , as: 'about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/postimage.rb
class Postimage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :postimages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    about_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/postimages_controller.rb
class PostimagesController < ApplicationController
  def new
    @postimage = Postimage.new
  end

  def index
  end

  def show
  end
  
  def create
    @postimage = Postimage.new(postimage_params)
    @postimage.user_id = current_user.id
    @postimage.save
    redirect_to postimages_path
  end
  
  
  private

  def postimage_params
    params.require(:postimage).permit(:shop_name, :image, :caption)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/postimages_helper.rb
module PostimagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshiterro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <header>
    <% if user_signed_in? %>
      <li>
        <%_ link_to '投稿フォーム',new_postimage_path %>
      </li>
    
      <li>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path %>
      </li>
    <% end %>
  </header>
    <%= yield %>
  </body>
</html>

app/views/postimages/index.html.erb
<h1>Postimages#index</h1>
<p>Find me in app/views/postimages/index.html.erb</p>

app/views/postimages/new.html.erb
<h1>画像投稿フォーム</h1>
  <%= form_with model: @postimage do |f| %>
    <h4>画像</h4>
      <%= f.file_field :image, accept: "image/*" %>
    <h4>ショップ名</h4>
      <%= f.text_field :shop_name %>
    <h4>説明</h4>
      <%= f.text_area :caption %>
    <%= f.submit '投稿' %>
  <% end %>

app/views/postimages/show.html.erb
<h1>Postimages#show</h1>
<p>Find me in app/views/postimages/show.html.erb</p>